当我们从多个数据源获取相关数据，或者数据集本身包括了多个表格，那就可能涉及一些数据连接或合并等操作。

# 1. concat()函数将两个df拼接
## 1.1纵向拼接，列名相同
axis 调整纵向0，还是横向1进行合并。合并时默认会把索引也进行合并，当索引编号无实在意义时，用ignore_index=True进行省略

pd.concat([df1, df2], ignore_index=True)

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    '商品名': ['iPhone 12', 'MacBook Air', 'iPad', 'Apple Watch Series 6'],
    '单价（元）': [6799, 8499, 3199, 2699],
    '颜色': ['蓝色', '金色', '灰色', '粉色'],
    '库存数量': [100, 50, 150, 80]
})


df2 = pd.DataFrame({
    '商品名': ['AirPods Pro', 'HomePod mini', 'Apple TV 4K', 'Beats Flex'],
    '单价（元）': [1599, 749, 1499, 399],
    '颜色': ['白色', '空间灰色', '黑色', '黄色'],
    '库存数量': [120, 80, 60, 200]
})

In [4]:
df1

                    商品名  单价（元）  颜色  库存数量
0             iPhone 12   6799  蓝色   100
1           MacBook Air   8499  金色    50
2                  iPad   3199  灰色   150
3  Apple Watch Series 6   2699  粉色    80

In [5]:
df2

            商品名  单价（元）    颜色  库存数量
0   AirPods Pro   1599    白色   120
1  HomePod mini    749  空间灰色    80
2   Apple TV 4K   1499    黑色    60
3    Beats Flex    399    黄色   200

纵向合并，且索引号也进行合并。还未忽略索引

In [6]:
pd.concat([df1,df2])

                    商品名  单价（元）    颜色  库存数量
0             iPhone 12   6799    蓝色   100
1           MacBook Air   8499    金色    50
2                  iPad   3199    灰色   150
3  Apple Watch Series 6   2699    粉色    80
0           AirPods Pro   1599    白色   120
1          HomePod mini    749  空间灰色    80
2           Apple TV 4K   1499    黑色    60
3            Beats Flex    399    黄色   200

忽略索引之后，索引会正常编号。

In [7]:
pd.concat([df1,df2],ignore_index=True)

                    商品名  单价（元）    颜色  库存数量
0             iPhone 12   6799    蓝色   100
1           MacBook Air   8499    金色    50
2                  iPad   3199    灰色   150
3  Apple Watch Series 6   2699    粉色    80
4           AirPods Pro   1599    白色   120
5          HomePod mini    749  空间灰色    80
6           Apple TV 4K   1499    黑色    60
7            Beats Flex    399    黄色   200

## 1.2纵向拼接，列名不完全相同
列名不同时，并不会产生报错，此时DataFrame的所有列都会被进行保留，匹配不上的地方，就会自动用NaN值进行填充

df3为`单价（元）`，df4为`单价`，并不完全相同

In [10]:
df3 = pd.DataFrame({
    '商品名': ['iPhone 12', 'MacBook Air', 'iPad', 'Apple Watch Series 6'],
    '单价（元）': [6799, 8499, 3199, 2699],
    '颜色': ['蓝色', '金色', '灰色', '粉色'],
    '库存数量': [100, 50, 150, 80]
})


df4 = pd.DataFrame({
    '商品名': ['AirPods Pro', 'HomePod mini', 'Apple TV 4K', 'Beats Flex'],
    '单价': [1599, 749, 1499, 399],
    '颜色': ['白色', '空间灰色', '黑色', '黄色'],
    '库存数量': [120, 80, 60, 200]
})

In [11]:
df3

                    商品名  单价（元）  颜色  库存数量
0             iPhone 12   6799  蓝色   100
1           MacBook Air   8499  金色    50
2                  iPad   3199  灰色   150
3  Apple Watch Series 6   2699  粉色    80

In [12]:
df4

            商品名    单价    颜色  库存数量
0   AirPods Pro  1599    白色   120
1  HomePod mini   749  空间灰色    80
2   Apple TV 4K  1499    黑色    60
3    Beats Flex   399    黄色   200

In [13]:
pd.concat([df3,df4],ignore_index=True)

                    商品名   单价（元）    颜色  库存数量      单价
0             iPhone 12  6799.0    蓝色   100     NaN
1           MacBook Air  8499.0    金色    50     NaN
2                  iPad  3199.0    灰色   150     NaN
3  Apple Watch Series 6  2699.0    粉色    80     NaN
4           AirPods Pro     NaN    白色   120  1599.0
5          HomePod mini     NaN  空间灰色    80   749.0
6           Apple TV 4K     NaN    黑色    60  1499.0
7            Beats Flex     NaN    黄色   200   399.0

这里需要用其他方法单价进行合并，暂时不表。

## 1.3横向拼接
用concat函数，传入可选参数axis=1

In [14]:
df5 = pd.DataFrame({
    '商品名': ['iPhone 12', 'MacBook Air', 'iPad', 'Apple Watch Series 6'],
    '单价（元）': [6799, 8499, 3199, 2699]
})


df6 = pd.DataFrame({
    '颜色': ['蓝色', '金色', '灰色', '粉色'],
    '库存数量': [100, 50, 150, 80]
})

In [15]:
df5

                    商品名  单价（元）
0             iPhone 12   6799
1           MacBook Air   8499
2                  iPad   3199
3  Apple Watch Series 6   2699

In [16]:
df6

   颜色  库存数量
0  蓝色   100
1  金色    50
2  灰色   150
3  粉色    80

In [17]:
pd.concat([df5,df6],axis = 1)

                    商品名  单价（元）  颜色  库存数量
0             iPhone 12   6799  蓝色   100
1           MacBook Air   8499  金色    50
2                  iPad   3199  灰色   150
3  Apple Watch Series 6   2699  粉色    80

# 2.merge 进行合并

concat()只是机械拼接，merge()基于一个或多个共同的“键”（key）来匹配行，将两个 DataFrame 按列拼接在一起。本质是一个横向（horizontal） 合并操作

## 2.1 指定列进行合并

pd.merge(df1, df2, on='列名')

In [19]:
customer_df = pd.DataFrame({
    '客户ID': [1, 2, 3, 4],
    '姓名': ['Amy', 'Bill', 'Cathy', 'Dave'],
    '邮箱': ['amy@xxx.com', 'bill@xxx.com', 'cat@xxx.com', 'dave@xxx.com']
})

order_df = pd.DataFrame({
    '订单ID': [1, 2, 3, 4, 5],
    '客户ID': [1, 1, 2, 4, 4],
    '销售额': [100, 50, 75, 90, 120]
})

In [20]:
customer_df

   客户ID     姓名            邮箱
0     1    Amy   amy@xxx.com
1     2   Bill  bill@xxx.com
2     3  Cathy   cat@xxx.com
3     4   Dave  dave@xxx.com

In [21]:
order_df

   订单ID  客户ID  销售额
0     1     1  100
1     2     1   50
2     3     2   75
3     4     4   90
4     5     4  120

In [22]:
pd.merge(customer_df,order_df,on = '客户ID')

   客户ID    姓名            邮箱  订单ID  销售额
0     1   Amy   amy@xxx.com     1  100
1     1   Amy   amy@xxx.com     2   50
2     2  Bill  bill@xxx.com     3   75
3     4  Dave  dave@xxx.com     4   90
4     4  Dave  dave@xxx.com     5  120

如上例子，我们只有把顾客信息和订单信息分开在两个表里面，相同信息才不会多次重复出现。

假设我们只有一个表，里面又有订单数据又有客户信息的话。如果客户1下单了50次，那她的姓名和邮箱，就会在这个表里面重复50次；特别是，如果当客户1更改邮箱，那所有出现了她邮箱信息的行，都得去进行更新；但是如果我们把订单数据和客户信息放在两个表中，我们就只需要更新客户信息表中的一行。

由上可知，把不同的信息分开在不同表中，实际上是一个最佳实践。

**因此，在数据分析中，经常需要对DataFrame进行合并。**

## 2.2 基于多列值进行合并

on=['列名1', '列名2'...]

在合并的时候根据多列的值，要求它们得同时匹配

In [23]:
order_df2 = pd.DataFrame({
    '订单ID': ['A001', 'A002', 'A003', 'A004'],
    '订单日期': ['2000-01-01', '2000-01-02', '2000-01-02', '2000-01-03'],
    '客户ID': ['C001', 'C002', 'C001', 'C003'],
    '销售额': [100, 200, 150, 300]
})

customer_df2 = pd.DataFrame({
    '客户ID': ['C001', 'C002', 'C003'],
    '姓名': ['张三', '李四', '王五'],
    '手机号': ['13512345678', '13612345678', '13712345678'],
    '订单日期': ['2000-01-01', '2000-01-02', '2000-01-03']
})

In [24]:
order_df2

   订单ID        订单日期  客户ID  销售额
0  A001  2000-01-01  C001  100
1  A002  2000-01-02  C002  200
2  A003  2000-01-02  C001  150
3  A004  2000-01-03  C003  300

In [25]:
customer_df2

   客户ID  姓名          手机号        订单日期
0  C001  张三  13512345678  2000-01-01
1  C002  李四  13612345678  2000-01-02
2  C003  王五  13712345678  2000-01-03

In [26]:
pd.merge(order_df2,customer_df2,on =['客户ID','订单日期'])

   订单ID        订单日期  客户ID  销售额  姓名          手机号
0  A001  2000-01-01  C001  100  张三  13512345678
1  A002  2000-01-02  C002  200  李四  13612345678
2  A004  2000-01-03  C003  300  王五  13712345678

评价：只有客户ID和订单日期都相同的，才会合并，否则就舍弃。C001有两个，但只有1号的是两个都有，2号的那个就舍弃了

## 2.3 列名不同，但含义相同

方案1. 对任一DataFrame列名，进行重命名

方案2. 把可选参数`on`,替换成`left_on`和`right_on`，给`left_on`传入的是左边DataFrame用于合并的列名，给`right_on`传入的是右边DataFrame用于合并的列名

   **合并后，原来的两个DataFrame的列都会保留，用于匹配的列的值一致**

In [27]:
order_df3 = pd.DataFrame({
    '订单ID': ['A001', 'A002', 'A003', 'A004'],
    '订单日期': ['2000-01-01', '2000-01-02', '2000-01-02', '2000-01-03'],
    '客户编号': ['C001', 'C002', 'C001', 'C003'],
    '销售额': [100, 200, 150, 300]
})

customer_df3 = pd.DataFrame({
    '客户ID': ['C001', 'C002', 'C003'],
    '姓名': ['张三', '李四', '王五'],
    '手机号': ['13512345678', '13612345678', '13712345678'],
    '交易日期': ['2000-01-01', '2000-01-02', '2000-01-03']
})

In [28]:
order_df3

   订单ID        订单日期  客户编号  销售额
0  A001  2000-01-01  C001  100
1  A002  2000-01-02  C002  200
2  A003  2000-01-02  C001  150
3  A004  2000-01-03  C003  300

In [29]:
customer_df3

   客户ID  姓名          手机号        交易日期
0  C001  张三  13512345678  2000-01-01
1  C002  李四  13612345678  2000-01-02
2  C003  王五  13712345678  2000-01-03

评价：交易日期和订单日期是一回事，客户编号和客户ID也是一回事，可以根据这两列进行配合合并

In [30]:
pd.merge(order_df3,customer_df3,left_on=['订单日期','客户编号'],right_on=['交易日期','客户ID'])

   订单ID        订单日期  客户编号  销售额  客户ID  姓名          手机号        交易日期
0  A001  2000-01-01  C001  100  C001  张三  13512345678  2000-01-01
1  A002  2000-01-02  C002  200  C002  李四  13612345678  2000-01-02
2  A004  2000-01-03  C003  300  C003  王五  13712345678  2000-01-03

## 2.4列名相同，都需保留

合并后，为了区分某个重名的列到底来自哪个表，merge函数会自动为列名的结尾加上后缀，'_x'表示来自第一个表，'_y'表示来自第二个表

1. 自定义后缀

   传入可选参数`suffixes=['第一个表的重名列的后缀', '第二个表的重名列的后缀']`

In [31]:
df7 = pd.DataFrame({'日期': ['2000-01-01', '2000-01-02', '2000-01-03'],
                    '店铺': ['A', 'B', 'C'],
                    '销售额': [100, 200, 300]})
df8 = pd.DataFrame({'日期': ['2000-01-02', '2000-01-03', '2000-01-04'],
                    '店铺': ['B', 'C', 'D'],
                    '销售额': [400, 500, 600]})

In [32]:
df7

           日期 店铺  销售额
0  2000-01-01  A  100
1  2000-01-02  B  200
2  2000-01-03  C  300

In [33]:
df8

           日期 店铺  销售额
0  2000-01-02  B  400
1  2000-01-03  C  500
2  2000-01-04  D  600

In [34]:
pd.merge(df7,df8, on = ['日期','店铺'])

           日期 店铺  销售额_x  销售额_y
0  2000-01-02  B    200    400
1  2000-01-03  C    300    500

In [36]:
pd.merge(df7,df8, on = ['日期','店铺'],suffixes = ['_df7','_df8'])

           日期 店铺  销售额_df7  销售额_df8
0  2000-01-02  B      200      400
1  2000-01-03  C      300      500

## 2.5合并类型

inner（内连接）	只保留左右两边键值都匹配的行   	**交集 (A ∩ B)**	  行数 ≤ 左表，≤ 右表

left（左连接）	保留左表全部行，右表有匹配则合并，无则填 NaN	**左表全集**	行数 = 左表行数

right（右连接）	保留右表全部行，左表有匹配则合并，无则填 NaN	**右表全集**	行数 = 右表行数

outer（外连接）	保留左右两边的全部行，不匹配的一侧填 NaN	**并集 (A ∪ B)**	行数 ≥ 左表，≥ 右表

可以给merge函数传入可选参数`how='合并类型'`，用来指定合并类型，默认合并类型是inner

In [37]:
customers_data = {
    '客户ID': [1, 2, 3, 4, 5],
    '姓名': ['Tom', 'Bob', 'Mary', 'Alice', 'John'],
    '年龄': [20, 35, 27, 19, 42]
}
customer_df4 = pd.DataFrame(customers_data)


orders_data = {
    '订单ID': [1001, 1002, 1003, 1004, 1005, 1006],
    '订单日期': ['2000-03-12', '2000-03-13', '2000-03-13', '2000-03-15', '2000-03-18', '2000-03-21'],
    '客户ID': [1, 1, 2, 6, 5, 3],
    '产品': ['A', 'B', 'C', 'D', 'E', 'F'],
    '数量': [2, 3, 1, 4, 5, 2]
}
order_df4 = pd.DataFrame(orders_data)

In [38]:
customer_df4

   客户ID     姓名  年龄
0     1    Tom  20
1     2    Bob  35
2     3   Mary  27
3     4  Alice  19
4     5   John  42

In [39]:
order_df4

   订单ID        订单日期  客户ID 产品  数量
0  1001  2000-03-12     1  A   2
1  1002  2000-03-13     1  B   3
2  1003  2000-03-13     2  C   1
3  1004  2000-03-15     6  D   4
4  1005  2000-03-18     5  E   5
5  1006  2000-03-21     3  F   2

评价：只有客户ID是可以用来匹配。

In [40]:
pd.merge(customer_df4,order_df4,on = '客户ID',how = 'inner')

   客户ID    姓名  年龄  订单ID        订单日期 产品  数量
0     1   Tom  20  1001  2000-03-12  A   2
1     1   Tom  20  1002  2000-03-13  B   3
2     2   Bob  35  1003  2000-03-13  C   1
3     3  Mary  27  1006  2000-03-21  F   2
4     5  John  42  1005  2000-03-18  E   5

评价：客户ID，两边交集为1235，其他的舍弃

In [41]:
pd.merge(customer_df4,order_df4,on = '客户ID',how = 'outer')

   客户ID     姓名    年龄    订单ID        订单日期   产品   数量
0     1    Tom  20.0  1001.0  2000-03-12    A  2.0
1     1    Tom  20.0  1002.0  2000-03-13    B  3.0
2     2    Bob  35.0  1003.0  2000-03-13    C  1.0
3     3   Mary  27.0  1006.0  2000-03-21    F  2.0
4     4  Alice  19.0     NaN         NaN  NaN  NaN
5     5   John  42.0  1005.0  2000-03-18    E  5.0
6     6    NaN   NaN  1004.0  2000-03-15    D  4.0

评价：客户ID的并集。没有的用nan

In [42]:
pd.merge(customer_df4,order_df4,on = '客户ID',how = 'left')

   客户ID     姓名  年龄    订单ID        订单日期   产品   数量
0     1    Tom  20  1001.0  2000-03-12    A  2.0
1     1    Tom  20  1002.0  2000-03-13    B  3.0
2     2    Bob  35  1003.0  2000-03-13    C  1.0
3     3   Mary  27  1006.0  2000-03-21    F  2.0
4     4  Alice  19     NaN         NaN  NaN  NaN
5     5   John  42  1005.0  2000-03-18    E  5.0

In [43]:
pd.merge(customer_df4,order_df4,on = '客户ID',how = 'right')

   客户ID    姓名    年龄  订单ID        订单日期 产品  数量
0     1   Tom  20.0  1001  2000-03-12  A   2
1     1   Tom  20.0  1002  2000-03-13  B   3
2     2   Bob  35.0  1003  2000-03-13  C   1
3     6   NaN   NaN  1004  2000-03-15  D   4
4     5  John  42.0  1005  2000-03-18  E   5
5     3  Mary  27.0  1006  2000-03-21  F   2

# 3.JOIN

join方法

join方法是根据索引去合并DataFrame，会保留两个DataFrame的所有的列

**假如有重名列，会报错，需要传入可选参数`lsuffix='左边DataFrame重名列的后缀'`和`rsuffix='右边DataFrame重名列的后缀'`**

**join是方法，不是函数，所以我们是要用某个DataFrame去调用**

**join方法也可以传入可选参数`how`，来指定去进行哪个类型的合并**

In [44]:
customer_df4

   客户ID     姓名  年龄
0     1    Tom  20
1     2    Bob  35
2     3   Mary  27
3     4  Alice  19
4     5   John  42

In [45]:
order_df4

   订单ID        订单日期  客户ID 产品  数量
0  1001  2000-03-12     1  A   2
1  1002  2000-03-13     1  B   3
2  1003  2000-03-13     2  C   1
3  1004  2000-03-15     6  D   4
4  1005  2000-03-18     5  E   5
5  1006  2000-03-21     3  F   2

In [46]:
customer_df4.join(order_df4, lsuffix='_customer', rsuffix='_order')

   客户ID_customer     姓名  年龄  订单ID        订单日期  客户ID_order 产品  数量
0              1    Tom  20  1001  2000-03-12           1  A   2
1              2    Bob  35  1002  2000-03-13           1  B   3
2              3   Mary  27  1003  2000-03-13           2  C   1
3              4  Alice  19  1004  2000-03-15           6  D   4
4              5   John  42  1005  2000-03-18           5  E   5

按索引把 order_df4 拼到 customer_df4 右边，如果列名冲突，左表加 _customer，右表加 _order。默认左连接（left join），以 `customer_df4` 的索引为准,0-4。