In [4]:
import pandas as pd
import numpy as np

# 1. groupby

In [5]:
df = pd.DataFrame({
    '分店编号': ['001', '002', '001', '002', '001', '002', '001', '002'],
    '时间段': ['2022Q1', '2022Q1', '2022Q1', '2022Q1', '2022Q2', '2022Q2', '2022Q2', '2022Q2'],
    '商品类别': ['生鲜食品', '生鲜食品', '休闲食品', '休闲食品', '生鲜食品', '生鲜食品', '休闲食品', '休闲食品'],
    '销售额': [1500, 2000, 3000, 2500, 1800, 2200, 3200, 2700],
    '销售数量': [105,  84, 171, 162,  67, 150,  99,  57]
})
df

  分店编号     时间段  商品类别   销售额  销售数量
0  001  2022Q1  生鲜食品  1500   105
1  002  2022Q1  生鲜食品  2000    84
2  001  2022Q1  休闲食品  3000   171
3  002  2022Q1  休闲食品  2500   162
4  001  2022Q2  生鲜食品  1800    67
5  002  2022Q2  生鲜食品  2200   150
6  001  2022Q2  休闲食品  3200    99
7  002  2022Q2  休闲食品  2700    57

In [7]:
# 把df针对分店编号进行分组，计算销售额平均值
df.groupby('分店编号')["销售额"].mean()

分店编号
001    2375.0
002    2350.0
Name: 销售额, dtype: float64

评价：

 （1）根据变量进行分组，得到一个叫做DataFrameGroupBy的实例——df.groupby('变量')

 本例中，根据分店编号，分成001和002两组数据。

（2）groupby方法，会自动把变量值相同的行分组组合到一起，并返回一个叫做DataFrameGroupBy的实例。

分组组合，可以看成把变量值相同的许多数据组合进，以组为单位的单元格中，这时一个单元格里面有多个数据，并不是有效的表格数据，无法返回DataFrame。

因此，最后需要通过聚合函数，生成有效表格数据。

（3）聚合函数包括：

count()，得到元素的数量

first()，得到第一个元素

last()，得到最后一个元素

mean()，得到所有元素平均值

median()，得到所有元素中位数

min()，得到所有元素最小值

max()，得到所有元素最大值

std()，得到所有元素的标准差

var()，得到所有元素的方差

prod()，得到所有元素的积

sum()，得到所有元素的和

In [9]:
# 把df针对分店编号进行分组，计算销售额、销售数量平均值
df.groupby('分店编号')[["销售额","销售数量"]].mean()

         销售额    销售数量
分店编号
001   2375.0  110.50
002   2350.0  113.25

In [10]:
#把df针对分店编号和时间段进行分组，计算销售额和销售数量的平均值
df.groupby(['分店编号','时间段'])[["销售额","销售数量"]].mean()

                销售额   销售数量
分店编号 时间段
001  2022Q1  2250.0  138.0
     2022Q2  2500.0   83.0
002  2022Q1  2250.0  123.0
     2022Q2  2450.0  103.5

评价：先按分店编号分组，再根据时间段分组，得到各组对应的平均值。

###  自定义聚合函数

自定义聚合函数的要求是，它能把Series里一堆数字汇总成一个数字.可以用apply方法，参数传入自定义聚合函数的函数名

In [11]:
def max_plus_10(nums):
    return nums.max() + 10

In [12]:
df.groupby(['分店编号','时间段'])[["销售额","销售数量"]].apply(max_plus_10)

              销售额  销售数量
分店编号 时间段
001  2022Q1  3010   181
     2022Q2  3210   109
002  2022Q1  2510   172
     2022Q2  2710   160

# 2. pivot_table()

pivot_table() 是 Pandas 最重要的统计分析函数之一，可以说是 Excel 数据透视表（Pivot Table） 在 Python 中的实现。

| 参数         | 作用            |
| ---------- | ------------- |
| data       | 数据源 DataFrame |
| values     | 要统计哪一列        |
| index      | 行分组依据         |
| columns    | 列分组依据         |
| aggfunc    | 聚合函数          |
| fill_value | 空值填充          |
| margins    | 是否增加总计        |

In [16]:
''' pd.pivot_table(
    data,
    values=None,
    index=None,
    columns=None,
    aggfunc=None,
    fill_value=None,
    margins=False
)'''

" pd.pivot_table(\n    data,\n    values=None,\n    index=None,\n    columns=None,\n    aggfunc='mean',\n    fill_value=None,\n    margins=False\n)"

In [17]:
df

  分店编号     时间段  商品类别   销售额  销售数量
0  001  2022Q1  生鲜食品  1500   105
1  002  2022Q1  生鲜食品  2000    84
2  001  2022Q1  休闲食品  3000   171
3  002  2022Q1  休闲食品  2500   162
4  001  2022Q2  生鲜食品  1800    67
5  002  2022Q2  生鲜食品  2200   150
6  001  2022Q2  休闲食品  3200    99
7  002  2022Q2  休闲食品  2700    57

In [23]:
#把df的分店编号和时间段作为索引，商品类别作为列，计算销售额的总和
pd.pivot_table(
    df,
    values = "销售额",
    index = ['分店编号','时间段'],
    columns = '商品类别',
    aggfunc = np.sum # 不传入函数时，默认是求平均
)

商品类别         休闲食品  生鲜食品
分店编号 时间段
001  2022Q1  3000  1500
     2022Q2  3200  1800
002  2022Q1  2500  2000
     2022Q2  2700  2200

In [27]:
#把df的商品类别作为索引，分店编号作为列，计算销售额的平均值
pd.pivot_table(
    df,
    values = "销售额",
    index = '商品类别',
    columns = '分店编号',
    aggfunc = ['mean','sum'] # 不传入函数时，默认是求平均
)

        mean           sum
分店编号     001     002   001   002
商品类别
休闲食品  3100.0  2600.0  6200  5200
生鲜食品  1650.0  2100.0  3300  4200